### ISSUE TITLE
Remove/split-out *.js.map files

### ISSUE THREAD

**Issue by jcrist** [conda-forge/jupyterlab-feedstock#155]
The `*.js.map` files are non-negligible in size:

```
$ find ./lib/python3.7/site-packages/jupyterlab ./share/jupyter/lab/ -type f,l -name '*.js.map' -exec du -hc {} +
 11M    ./lib/python3.7/site-packages/jupyterlab/static/vendors~main.490fadf8b0813d47d591.js.map
1.3M    ./lib/python3.7/site-packages/jupyterlab/static/0.8655c60128912e3ea900.js.map
4.0K    ./lib/python3.7/site-packages/jupyterlab/static/vega.0adc8a452b66056a4f6e.js.map
2.9M    ./lib/python3.7/site-packages/jupyterlab/static/vendors~vega.70a9a6945c18f5c12a42.js.map
 80K    ./lib/python3.7/site-packages/jupyterlab/static/main.78a97ae7d969b08570c6.js.map
 12K    ./lib/python3.7/site-packages/jupyterlab/static/3.41f272f8c07719e6ad4f.js.map
 11M    ./share/jupyter/lab//static/vendors~main.490fadf8b0813d47d591.js.map
1.3M    ./share/jupyter/lab//static/0.8655c60128912e3ea900.js.map
4.0K    ./share/jupyter/lab//static/vega.0adc8a452b66056a4f6e.js.map
2.9M    ./share/jupyter/lab//static/vendors~vega.70a9a6945c18f5c12a42.js.map
 80K    ./share/jupyter/lab//static/main.78a97ae7d969b08570c6.js.map
 12K    ./share/jupyter/lab//static/3.41f272f8c07719e6ad4f.js.map
 30M    total
```

When installing in a docker image, it may be useful to remove these (they also appear to be duplicated). Right now I'm removing these manually after installation, which is functional if not ideal.

**Comment by jakirkham** [comment]
Thanks for raising this and other package minimization requests, @jcrist.

I'd suggest since this is a common request for various packages that we raise [an issue on the webpage repo]( https://github.com/conda-forge/conda-forge.github.io/issues ) to discuss making this change more broadly. We might be able to solve this problem more efficiently (saving you and packagers time) by deciding how to handle this issue across all packages and thus automate the solution and it's rollout.

Does this sound reasonable? Thoughts?

**Comment by jasongrout** [comment]
Would you also file an issue with JupyterLab? Perhaps we could not ship these with the default build, and only build them if the user wants.

**Comment by jasongrout** [comment]
I've opened https://github.com/jupyterlab/jupyterlab/issues/7041 for the jupyterlab-specific case.
