### ISSUE TITLE
Depend on nodejs and ipywidgets?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/jupyterlab-feedstock#159]
I always find myself using the following fix
https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637

Does it make sense to depend on nodejs and ipywidgets?

**Comment by jasongrout** [comment]
Not on ipywidgets (jupyter widgets aren't distributed with jlab). One could see an argument for depending on node, but we wanted to keep the initial distribution of jlab pretty light. Since jlab itself does not depend on node unless you want to install extensions, we went with the minimal requirements.

**Comment by jakirkham** [comment]
Maybe we could document it in the post-link script instead or perhaps add a README in the `recipe` here?

**Comment by jasongrout** [comment]
What are you suggesting we document and for what audience? The decision mentioned above for future recipe authors? Or the fact that nodejs is needed to install extensions for users?

**Comment by jakirkham** [comment]
The latter.

**Comment by jasongrout** [comment]
Are you suggesting a message to the user? I thought any output from post-link scripts was not shown to the user, and we're going to get rid of the post-link scripts anyway soon.
